
* topic
	- main topic: temperature models of electric machines
	- goal: how to evaluate/estimate material properties/state of information if machine is running in the long run (> 20 years)
    => one approach is MOR
	  especially state of duration: (non)-linear model

* tactic
- idea: co-operate with Honza because matrix already given
- date before annual report (end of august)
- English-B2, terminate date (but exam not as import as annual report)!
- agros for creating geometry, extract matrices
- part by part reduce whole motor (really nice to pick particular parts of motors that can be reduced [non-reducabbe parts still ok]) combination of FEM and MOR

* remarks
- omit PETSc if MOR is sufficent
- start with POD (easiest method) (from snapshots of stiffness matrix)
- principle POD:
  - from square matrix get eivenval/eigenvec (these eigenvec generate square matrix as well)
  - take (biggest ~5) eigenval/eigenvec matrix rect then
  - multiply big matrix by these rect matrix

* current task [2/4]
- [X] contact Honza to share code: to grasp what's going on (specification of the probelm) described by BC, Coulomb
          - try to understand code
          - can use the code or not...up to me
          - piece of winding; goal was: create network (similar to elec) but here distribution of heat
          - take FEM to reduce it with given precision and obtain something more precise 
- [X] Honza can generate random winding around the slot, how did he do
- [ ] need to figure out how to get data by command line
- [-] Comsol: calculating snapshots (solutions of different parameter-values, solution matrix)
          - [-] try to make reduction POD (how decomposition work):
                    1. [X] create covariant matrix
                    2. [X] multiply by transpose matrix
                    3. [X] calcualte eigenvec/val of these matrix
                    4. [ ] thorough testing and cleaning is missing
* current questions [4/4]
- [X] Q: why MPh package? https://github.com/MPh-py/MPh
          - [X] Q: just more convenient to get data?
            A: just another approach to interact with Comsol, just a trial
- [X] Q: not more than 10E6(?) entries if export data (mesh, matrix... from Comsol (workaround or limitation?)
    A: yes, known limitation
- [X] Q: do I need to know matrix as a whole to decide how much 'energy' in system?
    A: yes, (big) solution matrix must be solved/calculated/given once
          - to decide how much one eigenvalue weights
          - to make responsible cutoff
- [X] Q: are we able to create random winding in Comsol (using script)
          - A: Agros can, Comsol can be tricky


